### ISSUE TITLE
Docker image on dockerhub is out of date

### ISSUE THREAD

**Issue by linted** [netboxlabs/pktvisor#10]
# What is the problem?
The steps to run the docker image in the ReadMe.md are either out of date, or inaccurate. When trying to run the docker image the following error occurs:
```
$ docker run --rm -it --net=host ns1labs/pktvisor pktvisor any
Usage:
      pktvisor [-p PORT] [-H HOST]
      pktvisor (-h | --help)

```

Adding the -H option to specify the host's network does not appear to fix the issue:
```
$ docker run --rm -it --net=host ns1labs/pktvisor pktvisor any -H 172.17.2.42/24
Usage:
      pktvisor [-p PORT] [-H HOST]
      pktvisor (-h | --help)
```

Ignoring the instructions and running it without the `any` option gives the following:
```
docker run --rm -it --net=host ns1labs/pktvisor pktvisor  -H 172.17.2.42
panic: Get http://172.17.2.42:10853/api/v1/metrics/window/5: dial tcp 172.17.2.42:10853: connect: connection refused

goroutine 36 [running]:
main.updateViews(0xc000184000)
	/src/cmd/pktvisor/pktvisor.go:595 +0x252
main.counter(0xc000184000)
	/src/cmd/pktvisor/pktvisor.go:690 +0x40
created by main.main
	/src/cmd/pktvisor/pktvisor.go:169 +0x1dd
```
This has goroutines in it, which is strange since there is no Go code present in this repo. Further investigation shows the docker image is 2 months old.

# Why does it matter?
Having a read me that doesn't match the current state of the project makes it difficult for new users to pick up your tool and start using it, lowering adoption rate. Also having a docker image on dockerhub that doesn't reflect anything in the currect opensource repo calls into question the security of the project.

# Possible solutions?
Push the latest build of the project to dockerhub or remove/document in the readme so that new users know they will need  to build the docker themselves.

**Comment by weyrick** [comment]
Hi @linted, thanks for writing. The Getting Started section of the readme has two different commands in it: one to start the collector deamon (which is written in C++), and the other to start the UI (which is written in golang https://github.com/ns1/pktvisor/blob/master/cmd/pktvisor/pktvisor.go). This means there are two different binaries in the container, and the commands are subtly different. 

You have a typo in your first command that is failing (which runs the deamon); you are missing a `d` on the end of `pktvisord` before `any` - it is correct in the readme:
`docker run --rm --net=host -d ns1labs/pktvisor pktvisord any`
Without the `d` it tries to run the UI, which indeed does not take the `any` argument, and is also correct in the readme:
`docker run -it --rm --net=host ns1labs/pktvisor pktvisor`
 
The container on dockerhub is the latest.

Please try that to confirm it works and let us know. At the least, we should make the point about the different command lines for the different binaries clearer.

**Comment by dhanush-raj** [comment]
@weyrick Hi, I am using the docker image in docker desktop in windows 10. (Using wsl2)
But I also getting the same error as him mentioned above.
Can you suggest me what to do?
I can share any other info you want to clarify the issue!

**Comment by weyrick** [comment]
Hi @dhanush-raj can you paste the exact command line you're using? That being said, we have not tested on windows at all.

**Comment by dhanush-raj** [comment]
Hi @weyrick , Thanks for your response. Here I am attaching a screenshot of what I am doing.
![Screenshot (717)](https://user-images.githubusercontent.com/23426277/98183359-ff2c1300-1f2d-11eb-8f90-2db9b0297f55.png)

**Comment by weyrick** [comment]
@dhanush-raj I do not see a problem here - it looks like the collector daemon ran in your first command after the pull, and then you ran the UI. Your last command with the -H is unnecessary. The -H option is for the collector daemon, not the UI. I updated the README to clarify this.

**Comment by dhanush-raj** [comment]
@weyrick I did what you told, but still no luck!
![Screenshot (723)](https://user-images.githubusercontent.com/23426277/98324472-5a373600-2012-11eb-9d3f-6a96e3a2f559.png)
![Screenshot (722)](https://user-images.githubusercontent.com/23426277/98324480-5efbea00-2012-11eb-8901-186d4d91eea2.png)

**Comment by weyrick** [comment]
Okay it looks like it's actually working ok, it's just not seeing any DNS traffic, likely it doesn't know the host IP. I suggest either trying to specify a specific interface rather than `any` (this way it might detect the IP automatically), or to use the `-H` argument to the collector daemon (_not_ the command line UI). Either way you will have to stop the collector daemon and restart it with new arguments. After that, you should rerun the command line UI in the exact same way as you are doing it above to test it.

**Comment by dhanush-raj** [comment]
As suggested by you, I got the following error.
![Screenshot (727)](https://user-images.githubusercontent.com/23426277/98427566-bc03a880-20c3-11eb-83ea-ee9d22cf532a.png)

when I used "netstat" there was no service listening on port 10583!

**Comment by dhanush-raj** [comment]
@weyrick Can you point out what's the issue?

**Comment by weyrick** [comment]
I'm guessing it is not finding the ethernet interface by those names - you should check the docker logs for the pktvisord container after it runs. Unfortunately I don't know the naming patterns for windows ethernet interfaces. It should be the same as for `tcpdump` though if you want to google that.

**Comment by weyrick** [comment]
I am going to close this issue for now, as it has diverged from the original intent. Please open a new issue if you think there is still a problem.
